# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    labels:
      - dependencies
    commit-message:
      prefix: build/deps
    cooldown:
      default-days: 3
    target-branch: main
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: ci
    cooldown:
      default-days: 3
    target-branch: main
