[tools]
uv = "latest"

[settings]
python.uv_venv_auto = "create|source"
python.compile = false

[settings.pipx]
uvx = true

[tasks.build]
description = "build CnGalCalendar"
run = "uv run cngal_calendar.py"
alias = ["default"]
