name: Build

permissions: {}

on:
  schedule:
    - cron: 0 18 * * * # 2:00 UTC+8 everyday
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write # required to make release
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
        with:
          install: true
          cache: true
          cache_key_prefix: "release"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - run: uv run cngal_calendar.py

      - name: upload as release
        run: gh release upload "${TAG}" --clobber output/cngal-*
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: continuous
