name: Test

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - output/**
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.14", "3.15-dev"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup project with mise
        id: setup-mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          install: true
          cache: true
          cache_key_prefix: "test"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest

      - run: uv run cngal_calendar.py
